# Dot product

### Important points:
1. Vectors (i.e. arrays) must be of same length. 

2. For *scalars* and *1-d arrays*, it behaves like **dot product** of vectors. But for *2-d or larger arrays* it behaves like **matrix multiplication**.

## 1. Product of scalars:

In [8]:
import numpy as np

a = 25
b = 5
print(np.dot(a,b))


125


## 2. Product of 1-d arrays

In [ ]:
import numpy as np

# Dot product between vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot = np.dot(a, b)      # Both a and b must have same length, other you will get error.

print(dot)   
print(a.shape)
print(b.shape)


32
(3,)
(3,)


In [5]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

mat1 = np.dot(A, B)          # Works for matrices
mat2 = A @ B                 # Preferred way
mat3 = np.matmul(A, B)       # Explicit matrix multiplication

print(A)
print("--------")
print(B)
print("--------")

print(mat1)
# [[19 22]
#  [43 50]]


[[1 2]
 [3 4]]
--------
[[5 6]
 [7 8]]
--------
[[19 22]
 [43 50]]
