## Basic operations on numpy arrays

In [5]:
import numpy as np

x = [1,2,3,4,5]

ar = np.array(x)

ar

array([1, 2, 3, 4, 5])

In [6]:
ar ** 2

ar + 2

ar - 9

ar / 5


array([0.2, 0.4, 0.6, 0.8, 1. ])

## Numpy Functions:

### 1. arange(start, stop, step)
  - Creates numpy array, starting from ***start***, going up to ***but not including*** `stop`, in increaments of `step`.

In [7]:
import numpy as np

ar = np.arange(4,25, 5)

print(f"type of result : {type(ar)}")
print(ar)

type of result : <class 'numpy.ndarray'>
[ 4  9 14 19 24]


In [8]:
List = [0,400]
print(*List)

0 400


## Dot product

In [9]:
import numpy as np

x = [1, 2, 3]
y = [1, 2]

print(np.dot(x,y))

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)