# Generate random numbers.

## Why is seed important?
- **Seed**: Initial values that determine the **sequence** of pseudorandom numbers.
- For each new **seed**, you will get a different sequence.

In [14]:
import numpy as np

np.random.seed(42)             # global seed
seq1 = np.random.randint(low=1, high=10, size=15)

np.random.seed(123)
seq2 = np.random.randint(1,10,15)

print(seq1)
print(seq2)

[7 4 8 5 7 3 7 8 5 4 8 8 3 6 5]
[3 3 7 2 4 7 2 1 2 1 1 4 5 1 1]


### Following example will strengthen the concept of 'seed'.

- In below example, I'm trying to proove a point that : **Are random numbers are generated sequentially when we have fixed set?**

In [15]:
import numpy as np

np.random.seed(42)


# Let's print the first 30 random numbers, of the sequence, whose seed = 42
for _ in range(30):
    print(np.random.randint(1,10),end=" ")
print()


#  first 10 numbers of the sequence
sequence_part_1 = []
for _ in range(10):
    sequence_part_1.append(np.random.randint(1, 10))
print(sequence_part_1)

# next 10 numbers of same sequence.
sequence_part_2 = [np.random.randint(1,10) for _ in range(10)]
print(sequence_part_2)

7 4 8 5 7 3 7 8 5 4 8 8 3 6 5 2 8 6 2 5 1 6 9 1 3 7 4 9 3 5 
[3, 7, 5, 9, 7, 2, 4, 9, 2, 9]
[5, 2, 4, 7, 8, 3, 1, 4, 2, 8]


#### I'm not getting output as expected. 
#### Why?
 - I generate 30 random numbers in the first loop. That **advances the 'internal PRNG state' by 30 steps**.

 - Then, `sequence_part_1` starts from the **31st random number**, not the 1st.

 - And `sequence_part_2` starts from the **41st random number**

**So, I need to reset the seed each time before generating those parts:**

In [16]:
import random

np.random.seed(42)
for _ in range(30):
    print(np.random.randint(1,10), end=" ")
print()

np.random.seed(42)
sequence_part_1 = [np.random.randint(1, 10) for _ in range(10)]
print(sequence_part_1)

# Now 'internal PRNG state' is at 11th step
sequence_part_2 = [np.random.randint(1, 10) for _ in range(10)]
print(sequence_part_2)


7 4 8 5 7 3 7 8 5 4 8 8 3 6 5 2 8 6 2 5 1 6 9 1 3 7 4 9 3 5 
[7, 4, 8, 5, 7, 3, 7, 8, 5, 4]
[8, 8, 3, 6, 5, 2, 8, 6, 2, 5]


#### So, yes we are getting random numbers sequentially.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## `np.random`  vs.  `np.random.default_rng()`

|  | `np.random` (Legacy) | `np.random.default_rng()` (Modern) |
|---------|----------------------|-----------------------------------|
| **Basic Type** | Global module functions | Object-based Generator |
| **State Management** | Uses shared global state | Each Generator has independent state |
| **Reproducibility** | Hard to control (affects all code) | Easy to isolate with separate generators |
| **Statistical Quality** | Some older algorithms with quirks | More modern, statistically sound methods |
| **Thread Safety** | Not safe for parallel use | Safe - use separate generators per thread |
| **Seeding** | `np.random.seed(123)` sets global seed | `rng = np.random.default_rng(123)` creates local seed |
| **Common Methods** | `random()`, `randint()`, `normal()`, `choice()`, `shuffle()` | `random()`, `integers()`, `normal()`, `choice()`, `shuffle()` |
| **Status** | Still works but discouraged | Recommended for all new code |

## Quick Example

```python
# Legacy approach (not recommended for new code)
import numpy as np
np.random.seed(42)
values = np.random.random(5)

# Modern approach (recommended)
rng = np.random.default_rng(42)
values = rng.random(5)
```

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [36]:
import numpy as np

random_numbers = np.random.rand()
rng = np.random.default_rng()
# Generate 5 random floats between 0 and 1


rng = np.random.default_rng(42)
uniform_samples = rng.random(5)
print("Uniform samples (0-1):", uniform_samples)

# Generate 5 random floats between 10 and 20
uniform_range = rng.uniform(10, 20, 5)
print("Uniform samples (10-20):", uniform_range)

Uniform samples (0-1): [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Uniform samples (10-20): [19.75622352 17.61139702 17.86064305 11.28113633 14.50385938]


In [7]:
single_float = np.random.random()
single_float

0.18249173045349998

## Basic functions : 

### 1. random() - Uniform Random Numbers
**Parameters:**
 - **size**: Output shape (int or tuple)

In [35]:
# Generate a single random float
single_float = rng.random()

# Generate a 2x3 array of random floats
array_floats = rng.random((2, 3))
print("2x3 array of uniform randoms:\n", array_floats)



2x3 array of uniform randoms:
 [[0.42510263 0.87941173 0.27034097]
 [0.89374313 0.42597096 0.32780772]]


### 2. integers() - Random Integers
**Parameters**:
 - **low**: Lower bound (inclusive)  

 - **high**: Upper bound (exclusive by default)  
 - **size**: Output shape
 - **endpoint**: Whether to include high value (default False)
 - **dtype**: Output data type

In [33]:
# Generate 10 random integers between 0 and 9
ints_0_9 = rng.integers(0, 10, 10)
print("Integers (0-9):", ints_0_9)

# Generate 10 random integers between 1 and 10 (inclusive)
ints_1_10 = rng.integers(1, 11, 10)  # Method 1
ints_1_10_alt = rng.integers(1, 10, 10, endpoint=True)  # Method 2
print("Integers (1-10):", ints_1_10)


Integers (0-9): [4 9 9 4 7 0 0 2 6 1]
Integers (1-10): [1 7 8 8 8 9 7 6 9 4]


### 3. choice() - Random Selection
**Parameters**:

- **a**: Array-like input to sample from (or int to sample from range)

- **size**: Output shape
- **replace**: Allow repeated selection (default True)
- **p**: Probability array for weighted selection


In [29]:
# Select 5 random letters from a list
letters = ['a', 'b', 'c', 'd', 'e']
selected = rng.choice(letters, 5, replace=True)
print("Selected letters:", selected)

# Select with custom weights
weighted = rng.choice(letters, 10, p=[0.1, 0.2, 0.4, 0.2, 0.1])
print("Weighted selection:", weighted)



Selected letters: ['b' 'b' 'c' 'd' 'e']
Weighted selection: ['d' 'd' 'c' 'd' 'd' 'c' 'b' 'c' 'b' 'b']


### 4. shuffle() - Random Permutation
**Parameters**:
 - **x**: Array to be shuffled (modified in-place)
 
 - **axis**: Axis along which to shuffle (default 0)

In [28]:
# Create and shuffle an array
arr = np.arange(10)
rng.shuffle(arr)
print("Shuffled array:", arr)

# For arrays with multiple dimensions
matrix = np.arange(12).reshape(3, 4)
print("Original matrix:\n", matrix)
rng.shuffle(matrix)  # Shuffles the rows by default
print("Shuffled matrix:\n", matrix)


Shuffled array: [5 4 9 6 0 7 8 1 2 3]
Original matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shuffled matrix:
 [[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]


### 5. permutation() - Return Shuffled Copy
**Parameters**:
 - **x** : Array or int  
 - **axis**: Axis along which to shuffle (default 0)

In [27]:
# Return a shuffled copy (original remains unchanged)
arr = np.arange(10)
shuffled = rng.permutation(arr)
print("Original:", arr)
print("Shuffled copy:", shuffled)

# From integer (equivalent to shuffled range)
perm_range = rng.permutation(10)
print("Permutation of range(10):", perm_range)

Original: [0 1 2 3 4 5 6 7 8 9]
Shuffled copy: [2 9 0 8 4 1 6 7 3 5]
Permutation of range(10): [6 3 8 2 9 5 1 7 4 0]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Distributions

### 1. Uniform : Generates numbers where **all values** in a range have **equal probability**.

In [ ]:
# Generate 5 random floats between 0 and 1,  random()
rng = np.random.default_rng(42)
uniform_samples = rng.random(5)
print("Uniform samples (0-1):", uniform_samples)


# uniform()
# Generate 5 random floats between 10 and 20
uniform_range = rng.uniform(10, 20, 5)
print("Uniform samples (10-20):", uniform_range)

Uniform samples (0-1): [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Uniform samples (10-20): [19.75622352 17.61139702 17.86064305 11.28113633 14.50385938]


**Note** :  we are using different functions for different ranges

### 2. Normal Distribution : normal()

- Generates numbers following **a bell curve centered around a mean**.  

- **normal()** funxn is used.
- **Parameters**:
    - **loc**: Mean (center) of distribution
    - **scale**: Standard deviation
    - **size**: Output shape


In [32]:
# Generate 1000 samples for a histogram
samples = rng.normal(loc=0, scale=1, size=50)
samples

array([-1.12295705,  0.76686729, -1.22470478,  1.15894958,  2.85743842,
        0.36645115,  0.58310814, -0.49285977, -1.81021332, -0.60271936,
       -1.09289524, -1.44700458,  1.72235994,  0.27286252,  0.37968758,
       -0.30902237, -0.17287108,  0.96455068, -0.03233712,  0.53069394,
       -0.1960043 , -0.34215289, -1.40691417, -1.97774906, -0.2615619 ,
        0.05649669, -1.28613004, -0.03447487,  0.05375256, -2.15600801,
       -0.91512466,  0.40726389,  0.38705873, -1.15367492,  0.15844805,
        1.02240723,  0.77707296, -0.09528579, -0.46797631, -0.62934448,
        0.46781978,  0.19510397,  0.62940401,  0.13187381,  0.81876395,
        0.09459253,  0.78468872,  0.87082277, -0.80452663, -1.80814405])

In [26]:
# Generate 5 values from standard normal distribution (mean=0, std=1)
normal_samples = rng.normal(0, 1, 5)
print("Normal samples (mean=0, std=1):", normal_samples)

# Generate 5 values with mean=100 and std=15
custom_normal = rng.normal(100, 15, 5)
print("Normal samples (mean=100, std=15):", custom_normal)

Normal samples (mean=0, std=1): [0.87939797 0.77779194 0.0660307  1.12724121 0.46750934]
Normal samples (mean=100, std=15): [ 87.11061306 105.53126176  85.61676099 113.17675452  99.25111134]
